import type { MonsterAdminFormState, MonsterSize } from "@/page/admin-monsters-create/types";

export const MONSTER_SIZES: MonsterSize[] = [
  "Tiny",
  "Small",
  "Medium",
  "Large",
  "Huge",
  "Gargantuan",
];

export const DEFAULT_MONSTER_ADMIN_FORM: MonsterAdminFormState = {
  abilityCha: "10",
  abilityCon: "10",
  abilityDex: "10",
  abilityInt: "10",
  abilityStr: "10",
  abilityWis: "10",
  actionsJson: "",
  actor: "admin-ui",
  alignment: "",
  armorClass: "",
  challengeRating: "",
  conditionImmunitiesText: "",
  createdBy: "admin-ui",
  crNumeric: "",
  damageImmunitiesText: "",
  damageResistancesText: "",
  damageVulnerabilitiesText: "",
  hitPoints: "",
  id: "",
  isPublished: false,
  languagesText: "",
  legendaryActionsJson: "",
  name: "",
  passivePerception: "",
  proficiencyBonus: "",
  reactionsJson: "",
  savingThrowsText: "",
  schemaVersion: "1",
  searchTokensText: "",
  senses: "",
  size: "Medium",
  skillsText: "",
  source: "SRD 5.1",
  specialAbilitiesJson: "",
  speed: "",
  spellListText: "",
  spellSlotsText: "",
  type: "",
  updatedBy: "admin-ui",
};
